### ISSUE TITLE
Request to support python 3.6 instead of only 3.8+

### ISSUE THREAD

**Issue by sstacha** [sstacha/django-docrootcms#2]
I have had a request to support python 3.6 instead of 3.8.  Since the main feature needed with the sutils copy folder manage.py commands I am going to look into something like trapping the error for the directory already exists and delete it then try again if that doesn't cause too much trouble or code.

**Comment by sstacha** [comment]
Reproduced.  Here is error output:

3.6.6 -> copy tree during update errors because directory already exists.  Try to do copy tree before the other 2 to see if we can solve this problem.  Trap for FileExistsError and delete the directory so we can refresh for < 3.8.  Also maybe TypeError...

Snippit output:

$ python manage.py docrootcms update
attempting to update docroot app and test files
module path from DISTUTILS.SYSCONFIG: /Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms
local path: .
heading_substring: # ------------------------ DOCROOT CMS SETTINGS ------------------------------------


we have substrings so searching new document.
we did not find start and or end so lets append
Successfully updated /Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/resources/docroot_settings_append.py to docroot/settings.py
heading_substring: # ------------------------ DOCROOT CMS URLS ------------------------------------


we have substrings so searching new document.
we did not find start and or end so lets append
Successfully updated /Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/resources/docroot_urls_append.py to docroot/urls.py
Copied /Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/resources to docroot/resources
Copied /Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/templates to docroot/resources/templates
Traceback (most recent call last):
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/management/commands/docrootcms.py", line 76, in update
    shutil.copytree(module_test_path, resources_path, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/management/commands/docrootcms.py", line 228, in handle
    self.stdout.write(self.style.WARNING(f'{self.update()}'))
  File "/Users/sstacha/.pyenv/versions/testdocroot/lib/python3.6/site-packages/docrootcms/management/commands/docrootcms.py", line 82, in update
    shutil.copytree(module_test_path, resources_path)
  File "/Users/sstacha/.pyenv/versions/3.6.6/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/Users/sstacha/.pyenv/versions/3.6.6/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'docroot/resources'

**Comment by sstacha** [comment]
I am closing this issue.  I did not get to it and now 3.6 is quite outdated.  I don't think it is worth adding the code to support the old version, especially with how easy it is to run inside a docker container with a specific python version so easily.
